package com.thisorthat.thisorthat

object GameData {

    val colors = listOf<String>("Red", "Green", "Blue","Yellow","Orange","Purple", "Silver", "Pink", "Lime")
    var game: Game =
        Game(
            1,
            2,
            "",
            mutableListOf(),
            0,
            1,
            "",
            "",
            "",
            "",
            0,
            1
        )
    var questions = mutableListOf<List<String>>(((listOf("Star Wars","Star Trek"))),
        (listOf("Putin", "Trump")),
        (listOf("Marmite","Jam")),
        (listOf("Crumpets","Toast")),
        (listOf("Pizza","Curry")),
        (listOf("Chinese","Indian")),
        (listOf("Golf","Tennis")),
        (listOf("Football","Rugby")),
        (listOf("Wooland","Seashore")),
        (listOf("Owl","Eagle")),
        (listOf("Dolphin","Whale")),
        (listOf("Bambi","Dumbo")),
        (listOf("Koala","Panda")),
        (listOf("Gorilla","Orangutan")),
        (listOf("Rice","Pasta")),
        (listOf("Bentley","Rolls")),
        (listOf("Landrover","Lexus")),
        (listOf("Jaguar","BMW")),
        (listOf("Mclaren","Ferrari")),
        (listOf("Gin","Vodka")),
        (listOf("Orange","Lemon")),
        (listOf("Apple","Pear")),
        (listOf("Beatles","Stones")),
        (listOf("Madonna","Minogue")),
        (listOf("Adele","Sheeran")),
        (listOf("ACDC","Guns'n'Roses")),
        (listOf("Federer","Nadal")),
        (listOf("Toy Story","Monsters Inc.")),
        (listOf("Star Trek","Star Wars")),
        (listOf("Lord of the Rings","Harry Potter")),
        (listOf("Legolas","Aragorn")),
        (listOf("Surfing","SnowBoard")),
        (listOf("Red Wine","White Wine")),
        (listOf("Brown Bread","White Bread")),
        (listOf("Butter","Margarine")),
        (listOf("Buried","Cremated")),
        (listOf("Sun","Moon")),
        (listOf("UK","USA")),
        (listOf("Spain","Portugal")),
        (listOf("Spain","France")),
        (listOf("Safari","Scuba")),
        (listOf("Australia","New Zealand")),
        (listOf("Paris","London")),
        (listOf("New York","Paris")),
        (listOf("London","New York")),
        (listOf("Labrador","Collie")),
        (listOf("Collie","Husky")),
        (listOf("Terrier","Bulldog")),
        (listOf("Tuna","Salmon")),
        (listOf("Blonde","Brunette")),
        (listOf("Disney","Pixar")),
        (listOf("Running","Cycling")),
        (listOf("Night In","Night Out")),
        (listOf("Hockey","Netball")),
        (listOf("Winter","Summer")),
        (listOf("Christmas","Easter")),
        (listOf("Xbox","PS4")),
        (listOf("Red","Blue")),
        (listOf("Tea","Coffee")),
        (listOf("Pub","Club")),
        (listOf("Guitar","Piano")),
        (listOf("Early Bird","Night Owl")),
        (listOf("Books","Films")),
        (listOf("Burger","Pizza")),
        (listOf("Tattoo","Piercing")),
        (listOf("KFC","McDonalds")),
        (listOf("MotorBike","Car")),
        (listOf("LA","New York")),
        (listOf("City","Countryside")),
        (listOf("Adidas","Nike")),
        (listOf("Rice","Pasta")),
        (listOf("Maddonna","Minogue")),
        (listOf("Spicy","Mild")),
        (listOf("The Office","Friends")),
        (listOf("Simpsons","South Park")),
        (listOf("Cat","Dog")),
        (listOf("Pop","Rock")),
        (listOf("Pancake","Waffle")),
        (listOf("Text","Call")),
        (listOf("Love","Money")),
        (listOf("Book","Movie")),
        (listOf("Comedy","Horror")),
        (listOf("Rain","Snow")),
        (listOf("Boat","Plane")),
        (listOf("Paint","Draw")),
        (listOf("Glasses","Contacts")),
        (listOf("Slim","Thicc")),
        (listOf("Spots","Dandruff")),
        (listOf("Mullet","Bald")),
        (listOf("Past","Future")),
        (listOf("Read","Write")),
        (listOf("Sing","Dance")),
        (listOf("Flowers","Trees")),
        (listOf("Phone","Computer")),
        (listOf("Lions","Bears")),
        (listOf("Milk","Juice")),
        (listOf("Gold","Silver")),
        (listOf("Google","Bing")),
        (listOf("Pandas","Whales")),
        (listOf("Puzzle","Boardgame")),
        (listOf("Sandals","Sneakers")),
        (listOf("Bagel","Toast")),
        (listOf("Pool","Sea")),
        (listOf("Sweet","Salty")),
        (listOf("Steak","Chicken")),
        (listOf("Alaska","Hawaii")),
        (listOf("Shower","Bath")),
        (listOf("TV","Movie")),
        (listOf("FaceBook","Twitter")),
        (listOf("Mountains","Beach")),
        (listOf("Digital","Analogue")),
        (listOf("Too Hot","Too Cold")),
        (listOf("Pasta","Pizza")),
        (listOf("Family","Friends")),
        (listOf("Marvel","DC")),
        (listOf("Book","Kindle")),
        (listOf("Ice Cream","Sorbet")),
        (listOf("Chocolate","Vanilla")),
        (listOf("Veggie","Meat")),
        (listOf("Bacon","Sausage")),
        (listOf("Well Done","Rare")),
        (listOf("Cherry","Raspberry")),
        (listOf("Lime","Blueberry")),
        (listOf("Chinese","Italian")),
        (listOf("Chips","Onion Rings")),
        (listOf("Rock","Country")),
        (listOf("Pop","Reggae")),
        (listOf("Jazz","Techno")),
        (listOf("Veggie","Meat")),
        (listOf("Play","Musical")),
        (listOf("Spiderman","Hulk")),
        (listOf("Messy","Clean")),
        (listOf("Modern","Rustic")),
        (listOf("Jet","Yacht")),
        (listOf("Manicure","Makeover")),
        (listOf("Poker","Chess")),
        (listOf("Paintball","GoKart")),
        (listOf("Zoo","Aquarium")),
        (listOf("Spa","Gym")),
        (listOf("Jamaica","Rio")),
        (listOf("Nerd","Jock")),
        (listOf("Actor","Model")),
        (listOf("PJs","Nude")),
        (listOf("Savings","Shopping")),
        (listOf("Shy","Outgoing")),
        (listOf("Introvert","Extrovert")),
        (listOf("Brains","Beauty")),
        (listOf("Mac","PC")),
        (listOf("Hero","Villain")),
        (listOf("Kisses","Hugs")),
        (listOf("Kids","Pets")),
        (listOf("Girls","Boys")),
        (listOf("Eyesight","Taste")),
        (listOf("Science","Arts")),
        (listOf("Crazy","Sane")),
        (listOf("Bikini","OnePiece")),
        (listOf("Alien Invasion","Global Plague")),
        (listOf("Ant","Dec")),
        (listOf("Army","Navy")),
        (listOf("Arrogant","Shy")),
        (listOf("Bald","Fat")),
        (listOf("Banana","Pear")),
        (listOf("Belgium","Holland")),
        (listOf("Bribery","Bullying")),
        (listOf("Bubonic Plague","Smallpox")),
        (listOf("Bully","Walkover")),
        (listOf("Bungalow","Flat")),
        (listOf("Chavs","Toffs")),
        (listOf("Chemistry","Biology")),
        (listOf("Commando","Paratrooper")),
        (listOf("Countdown","Pointless")),
        (listOf("Darts","Bowling")),
        (listOf("Beckham","Ronaldo")),
        (listOf("Binman","SewerMan")),
        (listOf("Earthquake","Tsunami")),
        (listOf("Immortal","Mortal")),
        (listOf("Face Lift","BoobJob")),
        (listOf("Farting","Burping")),
        (listOf("Fear","Hate")),
        (listOf("Fireman","Policeman")),
        (listOf("Florida","California")),
        (listOf("Eminem","SnoopDog")),
        (listOf("Dr Dre","50 Cent")),
        (listOf("Flintstones","Simpsons")),
        (listOf("Frog","Newt")),
        (listOf("Frozen","Cinderella")),
        (listOf("Zebra","Giraffe")),
        (listOf("Goat","Llama")),
        (listOf("HeatWave","BigFreeze")),
        (listOf("Hitler","Mussolini")),
        (listOf("IceCream","Lolipop")),
        (listOf("India","China")),
        (listOf("Ironman","Batman")),
        (listOf("Irritated","Bored")),
        (listOf("Itchy Bum","Spotty Face")),
        (listOf("Zebra","Giraffe")),
        (listOf("Jaguar","Lexus")),
        (listOf("Mao","Stalin")),
        (listOf("Trump","Obama")),
        (listOf("Bieber","Timberlake")),
        (listOf("KGB","FBI")),
        (listOf("Lambs","Hamsters")),
        (listOf("Landing","Takeoff")),
        (listOf("Lust","Love")),
        (listOf("Lying","Stealing")),
        (listOf("Massage","Sauna")),
        (listOf("Midnight","Midday")),
        (listOf("Monopoly","Risk")),
        (listOf("Mow Lawn","Groceries")),
        (listOf("Spock","Sherlock")),
        (listOf("No Money","No Friends")),
        (listOf("Nuclear Fallout","Pandemic")),
        (listOf("Oasis","Blur")),
        (listOf("Olympics","World Cup")),
        (listOf("One Arm","One Leg")),
        (listOf("Knight","Samurai")),
        (listOf("Ninja","Spy")),
        (listOf("Pancakes","Apple Pie")),
        (listOf("Peter Pan","Robin Hood")),
        (listOf("Pigs","Cows")),
        (listOf("Prawns","Squid")),
        (listOf("Pride","Courage")),
        (listOf("Puppies","Kittens")),
        (listOf("Rita Ora","Jessie J")),
        (listOf("Ryan Air","Easy Jet")),
        (listOf("Sailing","Camping")),
        (listOf("Scotland","Wales")),
        (listOf("SeaSick","Sunstroke")),
        (listOf("Skydive","ScoobaDive")),
        (listOf("Smelly Feet","Bad Breath")),
        (listOf("Snails","Slugs")),
        (listOf("Snakes","Spiders")),
        (listOf("Soap","Shower Gel")),
        (listOf("Space Travel","Time Travel")),
        (listOf("Mind Reader","Invisibility")),
        (listOf("Stabbed","Shot")),
        (listOf("Stubbed Toe","Electric shock")),
        (listOf("Stand on Lego","Impaled")),
        (listOf("Sunbed","Spray Tan")),
        (listOf("Sweden","Norway")),
        (listOf("Take That","One Direction")),
        (listOf("Terminator","Predator")),
        (listOf("Muppets","Simpsons")),
        (listOf("Tigers","Polar Bears")),
        (listOf("Time","Money")),
        (listOf("Tonsillitis","Migrane")),
        (listOf("Toothache","Back pain")),
        (listOf("Touchscreen","Mouse")),
        (listOf("Single","Partner")),
        (listOf("Ugly","Stupid")),
        (listOf("Vomit","Diaoreah")),
        (listOf("Washing","Ironing")),
        (listOf("Rap","Metal")),
        (listOf("Xmen","Avengers")),
        (listOf("Mauled","Bitten by Snake")),
        (listOf("Fear","Hate")),
        (listOf("XRay Eyes","Super Speed")),
        (listOf("Drunk","Stoned")),
        (listOf("Marble","Granite")),
        (listOf("Barcelona","Madrid")),
        (listOf("Texas","Florida")),
        (listOf("Bali","Fiji")),
        (listOf("Thailand","Japan")),
        (listOf("Skateboard","Rollerskates")),
        (listOf("Sprint","Marathon")),
        (listOf("Bidet","Toilet Roll")),
        (listOf("SAS","Navy Seals")),
        (listOf("TV","Radio")),
        (listOf("Yoghurt","Cream")),
        (listOf("Knocker","Doorbell")),
        (listOf("Native","Exotic")),
        (listOf("Cash","Card")),
        (listOf("Conker","Acorn")),
        (listOf("Pink","Blue")),
        (listOf("Water","Wine")),
        (listOf("Tablet","Laptop")),
        (listOf("Puffin","Pelican")),
        (listOf("Squid","Octopus")),
        (listOf("Turtle","Tortoise")),
        (listOf("Crab","Lobster")),
        (listOf("Stilton","Gouda")),
        (listOf("Aubergine","Peppers")),
        (listOf("Cucumber","Courgette")),
        (listOf("Onion","Leek")),
        (listOf("Basil","Parsley")),
        (listOf("Lupins","Lillys")),
        (listOf("Lawn","Patio")),
        (listOf("Moles","Mice")),
        (listOf("Mozart","Beethoven")),
        (listOf("Brussels","Peas")),
        (listOf("Folk","Country")),
        (listOf("Opera","Symphony")),
        (listOf("Haste","Perfection")),
        (listOf("Sail","Motor")),
        (listOf("Plane","Ferry")),
        (listOf("Cottage","Mansion")),
        (listOf("Castle","Palace")),
        (listOf("Hovel","Tent")),
        (listOf("Bread","Cake")),
        (listOf("Swan","Goose")),
        (listOf("Sausage","Salami")),
        (listOf("Pita","Naan")),
        (listOf("Church","Chapel")),
        (listOf("Rome","Venice")),
        (listOf("Rome","New York")),
        (listOf("Eminem","Katy Perry")),
        (listOf("Taylor Swift","Ed Sheeran")),
        (listOf("Ginger","Blind")),
        (listOf("Freckles","Clear")),
        (listOf("Romeo","Juliet")),
        (listOf("Trumpet","Saxophone")),
        (listOf("Violin","Cello")),
        (listOf("Jedi","Sith")),
        (listOf("Vader","Luke")),
        (listOf("Anakin","ObiWan")),
        (listOf("Volcano","Earthquake")),
        (listOf("Rave","Cinema")),
        (listOf("Swanlake","Nutcracker")),
        (listOf("Oboe","Flute")),
        (listOf("Spiders","Heights")),
        (listOf("80s","90s")),
        (listOf("90s","Noughties")),
        (listOf("Barbie","Bratz")),
        (listOf("Lego","Nerf")),
        (listOf("Christmas","Birthday")),
        (listOf("Mum","Dad")),
        (listOf("Grandma","Grandad")),
        (listOf("Virgin","Player")),
        (listOf("Snakes","Scorpion")),
        (listOf("Horoscopes","Nonsense")),
        (listOf("Zeus","Odin")),
        (listOf("Thor","Loki")),
        (listOf("WonderWoman","Black Widow")),
        (listOf("Ballpoint","Fountain")),
        (listOf("Letter","Text")),
        (listOf("Wooden","Carpet")),
        (listOf("Emerald","Ruby")),
        (listOf("Gold Digger","Worker")),
        (listOf("Paint","Wallpaper")),
        (listOf("Rowing","Swimming")),
        (listOf("Jumper","Hoodie")),
        (listOf("Ghetto","Posh")),
        (listOf("Spoiled","Deprived")),
        (listOf("Skinny","Large")),
        (listOf("Boxers","Y-fronts")),
        (listOf("Action","Rom-Com")),
        (listOf("Sci-Fi","Horror")),
        (listOf("Brave","Scared")),
        (listOf("BaseBall","BasketBall")),
        (listOf("Ice Hockey","Hockey")),
        (listOf("Viking","Celtic")),
        (listOf("Cersei","Daenerys")),
        (listOf("Lannister","Stark")),
        (listOf("North","South")),
        (listOf("East","West")),
        (listOf("Spicy","Plain")),
        (listOf("Amber","Pearls")),
        (listOf("Normal","Weirdo")),
        (listOf("Melon","Mango")),
        (listOf("Jazz","Classical")),
        (listOf("God","Nature")),
        (listOf("Cheap","Expensive")),
        (listOf("Afterlife","Oblivion")),
        (listOf("Fallon","Kimmel")),
        (listOf("Corden","Conan")),
        (listOf("Colin Firth","Hugh Grant")),
        (listOf("Power Puff","Power Ranger")),
        (listOf("Hobbit","LOTR")),
        (listOf("Pooh","Paddington")),
        (listOf("Scooby","Shaggy")),
        (listOf("Velma","Daphney")),
        (listOf("Sesame St.","Muppets")),
        (listOf("Ghostbusters","Myth Busters")),
        (listOf("Jackass","Borat")),
        (listOf("3 Muskateers","3 Little Pigs")),
        (listOf("Donkey","Puss")),
        (listOf("Indiana Jones","Star Wars")),
        (listOf("Children","Adults")),
        (listOf("TeleTubbies","Tweenies")),
        (listOf("Rainbow","Waterfall")),
        (listOf("Shrek","Fiona")),
        (listOf("Charming","Rude")),
        (listOf("Old","Young")),
        (listOf("Beyonce","Rhianna")),
        (listOf("Russia","USA")),
        (listOf("Pro Gun","Anti Gun")),
        (listOf("Pro Life","Pro Choice")),
        (listOf("Love Actually","Bridget Jones")),
        (listOf("Alive","Dead")),
        (listOf("Vacation","Staycation")),
        (listOf("Past","Future")),
        (listOf("Tent","Cabin")),
        (listOf("Taylor Swift","Kanye")),
        (listOf("Camping","Glamping")),
        (listOf("Abs","Dad Bod")),
        (listOf("Headphones","Earphones")),
        (listOf("Earwax","Bogeys")),
        (listOf("Eyebrows","MonoBrow")),
        (listOf("Wireless","Wired")),
        (listOf("Cycle","Walk")),
        (listOf("SideWalk","Pavement")),
        (listOf("Cheesecake","Cheese")),
        (listOf("Custard","Cream")),
        (listOf("Cider","Beer")),
        (listOf("Beer","Wine")),
        (listOf("Indoor","Outdoor")),
        (listOf("Minister","President")),
        (listOf("Messi","Ronaldo")),
        (listOf("Heaven","Hell")),
        (listOf("Angel","Demon")),
        (listOf("God","Devil")),
        (listOf("Dictator","Democracy")),
        (listOf("Boobs","Bum")),
        (listOf("Spoon","Fork")),
        (listOf("Sofa","Couch")),
        (listOf("Pen","Pencil")),
        (listOf("Stand","Sit")),
        (listOf("Fold","Scrunch")),
        (listOf("Shaved","Smooth")),
        (listOf("Mouse","Rat")),
        (listOf("Mole","Vole")),
        (listOf("Oscar","Bafta")),
        (listOf("Fries","Wedges")),
        (listOf("Zeus","Poseidon")),
        (listOf("Hercules","Achilles")),
        (listOf("BBC","ITV")),
        (listOf("Netflix","Prime")),
        (listOf("Amazon","Ebay")),
        (listOf("Netflix","Disney")),
        (listOf("Chrome","Firefox")),
        (listOf("Hollister","Jack Wills")),
        (listOf("Zombies","Ghosts")),
        (listOf("Nerf Gun","Air Rifle")),
        (listOf("PaintBall","Airsoft")),
        (listOf("Death Penalty","Life Sentence")),
        (listOf("Poo","Pee")),
        (listOf("Simp","Chad")),
        (listOf("Fire","Water")),
        (listOf("Earth","Air")),
        (listOf("Pokemon","Yu'gioh!")),
        (listOf("Chlamydia","Herpes")),
        (listOf("Kidney","Bladder")),
        (listOf("Heart","Brain")),
        (listOf("Big Ben","Eiffel")),
        (listOf("Nose","Mouth")),
        (listOf("Fingers","Toes")),
        (listOf("Inny","Outy")),
        (listOf("3 Nipples","6 Nipples")),
        (listOf("Lake","Ocean")),
        (listOf("Road Trip","Cruise")),
        (listOf("Soul","No Soul")),
        (listOf("Computer","TV")),
        (listOf("Speakers","Headphones")),
        (listOf("Mario","Luigi")),
        (listOf("Toad","Peach")),
        (listOf("Mario Bros","Mario Kart")),
        (listOf("Soul","No Soul")),
        (listOf("Saving","Spending")),
        (listOf("1st Class","Economy")),
        (listOf("Hamilton","Vettel")),
        (listOf("Goatie","SideBurns")),
        (listOf("SuperGlue","PritStick")),
        (listOf("Tacos","Burgers")),
        (listOf("Chillis","Wendies")),
        (listOf("Sci-Fi","Fantasy")),
        (listOf("Brother","Sister")),
        (listOf("Ying","Yang")),
        (listOf("Light","Dark")),
        (listOf("Striped","Checked")),
        (listOf("Llama","Alpaca")),
        (listOf("Cash","Cheque")),
        (listOf("Stairs","Lift")),
        (listOf("Balloons","Party Poppers")),
        (listOf("WTF","OMG")),
        (listOf("Handmade","Shop")),
        (listOf("Front","Back")),
        (listOf("Barcelona","Madrid")),
        (listOf("Pizza","Pasta")),
        (listOf("Milan","Paris")),
        (listOf("Tudor","Victorian")),
        (listOf("Tuna","Mackeral")),
        (listOf("Lice","Worms")),
        (listOf("Logan Paul","KSI")),
        (listOf("Constipated","Diarrhea")),
        (listOf("Warhammer","Warcraft")),
        (listOf("Treadmill","Weights")),
        (listOf("Squats","Lunges")),
        (listOf("Press up","Burpie")),
        (listOf("Tinder","Bumble")),
        (listOf("Brains","Braun")),
        (listOf("Sword","Shield")),
        (listOf("Condom","Pill")),
        (listOf("Fight","Flight")),
        (listOf("Sunset","Sunrise")),
        (listOf("Bag","Briefcase")),
        (listOf("Suit","Casual")),
        (listOf("Shaken","Stirred")),
        (listOf("Skinny Dip","Skydive")),
        (listOf("Ruler","Estimate")),
        (listOf("Miles","Kilometers")),
        (listOf("Spades","Diamonds")),
        (listOf("Hearts","Clubs")),
        (listOf("Spade","Bucket")),
        (listOf("Minecraft","Roblox")),
        (listOf("Fortnite","Warzone")),
        (listOf("Laser Quest","Paintball")),
        (listOf("In Store","Online")),
        (listOf("Beige","White")),
        (listOf("Gray","White")),
        (listOf("Lemon","Lime")),
        (listOf("Cucumber","Aubergine")),
        (listOf("Parmesan","Parmaham")),
        (listOf("Risk","Reward")),
        (listOf("Sink","Swim")),
        (listOf("Brain","Mind")),
        (listOf("Nature","Nurture")),
        (listOf("BladeRunner","Matrix")),
        (listOf("Prequel","Sequel")),
        (listOf("Money","Power")),
        (listOf("Hansel","Gretal")),
        (listOf("Twitch","Youtube")),
        (listOf("Candle","Torch")),
        (listOf("Caterpillar","Butterfly")),
        (listOf("Bitcoin","Cash")),
        (listOf("Tesla","Ford")),
        (listOf("Wind","Solar")),
        (listOf("Battery","Wired")),
        (listOf("Nandos","KFC")),
        (listOf("News","Fake News")),
        (listOf("NASA","SpaceX")),
        (listOf("Fruits","Vegetables")))




    fun reset(){
        game.rounds = 1
        game.players = 2
        game.playerColor=""
        game.gameColors = mutableListOf()
        game.yourTurn = 0
        game.currentTurn = 1
        game.currentChoice = ""
        game.currentOption1 = ""
        game.currentOption2 = ""
        game.myGuess = ""
        game.myScore = 0
        game.Round = 1
    }

    fun stats(){
        println("ROUNDS "+ game.rounds)
        println("PLAYERS "+ game.players)
        println("PLAYERCOLOUR "+ game.playerColor)
        println("GAMECOLOURS "+ game.gameColors)
        println("YOURTURN " + game.yourTurn)
        println("CURRENTTURN "+ game.currentTurn)
        println("CURRENTCHOICE "+ game.currentChoice)
        println("CURRENTGUESS "+ game.myGuess)
        println("MYSCORE "+ game.myScore)
    }

}